### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by alavigne12** [pugetsoundandvision/videotools#15]
- "Remove original AIP after syncing" is not currently working. Original AIP is always left in place.

- Consider adding option to delete original MKV. May be done by incorporating an additional QC step, where the newly created MKV and MP4 are verified (same file size, same duration, etc.) as original MKV. If both files verify, original MKV is deleted. We would need to incorporate a rule where the MP4 only needs to match the MKV duration if it was created during the process of making the AIP. If an MP4 was already extant, it is likely a different duration than the original MKV.

**Comment by privatezero** [comment]
sync issue should be fixed  - closing
