### ISSUE TITLE
homebrew tap / cask is broken?

### ISSUE THREAD

**Issue by rowe-morehouse** [pugetsoundandvision/videotools#24]
I think there is something wrong with the `brew tap` or `cask`?

$ brew tap pugetsoundandvision/pugetsoundandvision && brew install cask

Errors:

```
==> Tapping pugetsoundandvision/pugetsoundandvision
Cloning into '/usr/local/Homebrew/Library/Taps/pugetsoundandvision/homebrew-pugetsoundandvision'...
remote: Enumerating objects: 251, done.
remote: Total 251 (delta 0), reused 0 (delta 0), pack-reused 251
Receiving objects: 100% (251/251), 40.51 KiB | 1011.00 KiB/s, done.
Resolving deltas: 100% (107/107), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/pugetsoundandvision/homebrew-pugetsoundandvision/audioqc.rb
No available formula with the name "audioqc".
In formula file: /usr/local/Homebrew/Library/Taps/pugetsoundandvision/homebrew-pugetsoundandvision/audioqc.rb
Expected to find class Audioqc, but only found: Audiotools.
Error: Cannot tap pugetsoundandvision/pugetsoundandvision: invalid syntax in tap!
```

Also, I see this is the newest release:

2021-01-05  
@privatezero privatezero released this on Jan 5

Will \`homebrew\` install this newest release?

Thanks in advance! :)

**Comment by privatezero** [comment]
hi @rowe-morehouse, thanks for reporting that! The Homebrew tap was in fact broken as it had a legacy formula floating around that was causing issues. I've deleted that formula so things _should_ be working again.

Yes - if things are working again, Homebrew should install that latest release, which included a fix for the brew `baggit` formula switching from the java script to the python script.

**Comment by rowe-morehouse** [comment]
thanks!
