### ISSUE TITLE
videoaip -h command

### ISSUE THREAD

**Issue by eddycolloton** [pugetsoundandvision/videotools#4]
When I run the videoaip -h command I'm getting "Input could not be found. Please enter valid input." Has -h been written?

**Comment by privatezero** [comment]
oh crap! Thanks for flagging this! I had put some initial crappy help into the -h command, but I haven't made a new release that incorporates it yet! I'll make a couple tweaks and push a release this morning.

Let me know any other problems/suggestions!!

**Comment by privatezero** [comment]
(still need to do things like update screenshots in the readme as well)

**Comment by eddycolloton** [comment]
I'm only just playing with it today but hope to be using it more often in the coming months. It's a great tool! I'll be sure to keep in touch as I use it more.

**Comment by privatezero** [comment]
Just pushed a new release, so a `brew update && brew upgrade` should fix this problem!

Thanks again for testing it out! In terms of things like sidecar metadata it is pretty stripped down, so definitely let me know if you think there is other info that should be captured!

**Comment by eddycolloton** [comment]
yup! ran the update and videoaip -h now displays: 
"Usage: videoaip [inputfile], help mode: videoaip -h, crop mode: videoaip -c, configuration: videoaip -e."

Closing issue. Thanks bud.
